name ?= c2patxt
python_version ?= 3.10 # Lowest compatible version (see pyproject.toml requires-python)
version_full ?= $(shell $(MAKE) --silent version-full)
version_small ?= $(shell $(MAKE) --silent version)

vectors_dir := tests/vectors

version:
	@bash ./cicd/version.sh -g . -c

version-full:
	@bash ./cicd/version.sh -g . -c -m

version-pypi:
	@bash ./cicd/version.sh -g .

install:
	uv venv --python $(python_version) --allow-existing
	$(MAKE) install-deps

install-deps:
	uv sync --extra dev --extra trust

upgrade:
	uv lock --upgrade --refresh

test:
	$(MAKE) test-static
	$(MAKE) test-func

test-static:
	uv run ruff format --check .
	uv run ruff check .
	uv run pyright .
	# NO EXPLICIT PATH. An argument here overrides [tool.vulture] paths in
	# pyproject.toml, which is how "vulture ." came to scan build/ -- a gitignored
	# artefact regenerated by the sdist test -- and report a stale finding about a
	# file ruff had already fixed in src/. A finding that appears and disappears with
	# an unrelated test trains people to ignore vulture.
	uv run -m vulture

# Every test except the benchmarks. Selection is by DIRECTORY, not by marker -- see
# CONTRIBUTING.md for why. Dropping the old `vectors` marker gave up one selection no
# path expresses, replaying the published conformance corpus across eight files; that
# is a deliberate trade rather than a free simplification.
test-func:
	uv run pytest tests/ -v -n auto --ignore=tests/benchmarks

# CodSpeed benchmarks (serial execution, no coverage).
#
# -o "addopts=" is load-bearing, not tidiness. Without it this inherits
# --cov-fail-under=90, -n auto, --timeout=30 and --disable-socket from pyproject.
# Coverage is the fatal one: its trace hook inflates the very figure simulation mode
# reports -- a modelled CYCLE ESTIMATE since runner v5, not the raw instruction count
# this comment used to claim.
#
# -p no:xdist is NOT belt-and-braces, and calling it that was wrong. It is what makes
# the drift case fail LOUDLY: if -o "addopts=" is ever dropped, the inherited -n auto
# meets -p no:xdist and pytest exits 4 with "unrecognized arguments: -n", instead of
# quietly benchmarking under coverage and eight workers.
#
# PYTEST_ADDOPTS is the one thing -o "addopts=" cannot clear -- pytest prepends it to
# argv independently of the ini option. codspeed.yml empties it in the job env.
#
# CI runs this same target rather than repeating the flags, so the two cannot drift.
test-bench:
	uv run pytest tests/benchmarks/ --codspeed -v --no-cov -p no:xdist -o "addopts="

# Fix what can be fixed, then run the full static gate: all four steps, because a
# contributor is told this target IS the gate.
lint:
	uv run ruff format .
	uv run ruff check --fix .
	uv run pyright .
	uv run -m vulture

# --- Test vectors -------------------------------------------------------------
# Vectors are COMMITTED, not fetched at test time; the suite runs offline.
# These targets refresh them from upstream. Pattern follows hpke-http.

download-vectors:
	$(MAKE) download-vectors-third-party
	$(MAKE) download-vectors-cose
	$(MAKE) download-vectors-cbor

# COSE_Sign1 examples from the COSE working group. Unlicense (public domain).
# eddsa-* use Ed25519 (alg -8), the only algorithm THIS PACKAGE accepts. 13.2.1's
# list is wider; within EdDSA it permits no instance but Ed25519.
# sign1-* add three passing and six FAILING cases.
download-vectors-cose:
	@echo "Downloading COSE_Sign1 vectors (cose-wg/Examples, Unlicense)..."
	@mkdir -p $(vectors_dir)/cose
	@for f in eddsa-examples/eddsa-01 eddsa-examples/eddsa-sig-01 eddsa-examples/eddsa-sig-02 \
	          sign1-tests/sign-pass-01 sign1-tests/sign-pass-02 sign1-tests/sign-pass-03 \
	          sign1-tests/sign-fail-01 sign1-tests/sign-fail-02 sign1-tests/sign-fail-03 \
	          sign1-tests/sign-fail-04 sign1-tests/sign-fail-06 sign1-tests/sign-fail-07; do \
	  curl -sSfL "https://raw.githubusercontent.com/cose-wg/Examples/master/$$f.json" \
	    -o "$(vectors_dir)/cose/$$(basename $$f).json"; \
	done
	@echo "  $$(ls $(vectors_dir)/cose/*.json | wc -l | tr -d ' ') COSE vector file(s)"

# RFC 8949 Appendix A, from the CBOR working group. BSD-2-Clause.
# NOT cbor/test-vectors: unmaintained since 2019 and shipping no licence at all.
download-vectors-cbor:
	@echo "Downloading CBOR vectors (cbor-wg/cbor-test-vectors, BSD-2-Clause)..."
	@mkdir -p $(vectors_dir)/cbor
	@for m in 0 1 2 3 4 5 6 7-float 7-simple; do \
	  curl -sSfL "https://raw.githubusercontent.com/cbor-wg/cbor-test-vectors/main/tests/rfc8949-appendixA/mt$$m.cbor" \
	    -o "$(vectors_dir)/cbor/mt$$m.cbor"; \
	  curl -sSfL "https://raw.githubusercontent.com/cbor-wg/cbor-test-vectors/main/tests/rfc8949-appendixA/mt$$m.edn" \
	    -o "$(vectors_dir)/cbor/mt$$m.edn"; \
	done
	@echo "  $$(ls $(vectors_dir)/cbor/mt*.cbor | wc -l | tr -d ' ') CBOR major-type file(s)"

download-vectors-third-party:
	@echo "Downloading third-party A.8 vectors for interop cross-checks..."
	@mkdir -p $(vectors_dir)/third_party
	@curl -sSfL "https://raw.githubusercontent.com/encypherai/c2pa-text/main/golden/vectors.json" \
		-o $(vectors_dir)/third_party/encypher-golden-vectors.json
	@curl -sSfL "https://raw.githubusercontent.com/writerslogic/c2pa-text-binding/main/vectors/a8-variation-selector.json" \
		-o $(vectors_dir)/third_party/writerslogic-a8-variation-selector.json
	@uv run python -c "\
import json; \
e = json.load(open('$(vectors_dir)/third_party/encypher-golden-vectors.json')); \
w = json.load(open('$(vectors_dir)/third_party/writerslogic-a8-variation-selector.json')); \
print(f'  EncypherAI: {len(e[\"unstructured_embed\"])} unstructured vector(s)'); \
print(f'  writerslogic: {len(w[\"byteToVariationSelector\"])} mapping entries, 1 wrapper vector')"

checksums:
# -prune on __pycache__ is load-bearing: without it the manifest listed two .pyc
# files, so `shasum -c SHA256SUMS` passed only on the machine that generated them and
# FAILED on every clean checkout and every other Python version. tests/vectors/README
# tells consumers to run that check, and an integrity manifest that cannot pass is
# worse than none -- especially for an artefact offered to C2PA and C2SP.
	@cd $(vectors_dir) && find . -type f ! -name SHA256SUMS ! -path '*/__pycache__/*' ! -name '*.pyc' \
	  | sort | xargs shasum -a 256 > SHA256SUMS \
	  && shasum -a 256 -c SHA256SUMS | tail -1 \
	  && echo "  $$(grep -c '' SHA256SUMS) vector file(s) checksummed"
