"""The vector file's own invariants. These must hold before any codec exists."""

from __future__ import annotations

import pytest

from tests.vectors.loader import VECTOR_FILE, Vector, load_vectors, vector_id

VECTORS = load_vectors()


def test_data_portion_is_pure_ascii() -> None:
    """The file must survive editors, terminals, git diff and code review.

    Its subject matter is invisible characters. Storing them literally is how a
    vector corpus silently rots. NormalizationTest.txt applies the same rule.
    """
    raw = VECTOR_FILE.read_bytes()
    offenders = [(i, b) for i, b in enumerate(raw) if b > 0x7F]
    assert offenders == [], f"non-ASCII bytes at {offenders[:5]}"


def test_file_has_no_byte_order_mark() -> None:
    """A vector file about U+FEFF must not itself start with U+FEFF."""
    assert not VECTOR_FILE.read_bytes().startswith(b"\xef\xbb\xbf")


def test_line_endings_are_lf_only() -> None:
    assert b"\r" not in VECTOR_FILE.read_bytes()


def test_records_parse_and_ids_are_unique() -> None:
    assert VECTORS, "vector file yielded no records"
    ids = [v.id for v in VECTORS]
    assert len(ids) == len(set(ids)), "record ids must be unique and never reused"


@pytest.mark.parametrize("vector", VECTORS, ids=vector_id)
def test_record_shape_matches_its_status(vector: Vector) -> None:
    """Status governs which fields must be populated."""
    assert vector.op in {"embed", "extract"}
    assert vector.text != b"" or "no-wrapper" in vector.flags or vector.id.startswith("X")
    if vector.is_ok:
        # An empty `expect` normally means the author forgot to fill the column. It is
        # a real value for exactly one shape -- a wrapper declaring manifestLength 0 --
        # so that shape carries a flag saying the emptiness is the point.
        assert vector.expect != b"" or "empty-manifest" in vector.flags, "an OK record must state its expected bytes"
    else:
        assert vector.expect == b"", "a failure record must not state expected bytes"
        assert vector.status == "NONE" or "." in vector.status, (
            "a failure status must be NONE or a dotted C2PA status code"
        )


def test_failure_statuses_are_spec_code_strings() -> None:
    """Codes are the specification's own strings, never paraphrases.

    A user who reads our error and searches the C2PA specification must land on
    the right clause.
    """
    known = {
        "OK",
        "NONE",
        "manifest.text.corruptedWrapper",
        "manifest.text.multipleWrappers",
        "assertion.dataHash.mismatch",
        "assertion.dataHash.malformed",
    }
    unknown = {v.status for v in VECTORS} - known
    assert unknown == set(), f"unrecognised status codes: {unknown}"


def test_every_flag_is_documented_in_the_header() -> None:
    """A flag nobody documented is a flag nobody can act on."""
    header = VECTOR_FILE.read_text("ascii").split("@Part0")[0]
    for vector in VECTORS:
        for flag in vector.flags:
            assert f"\n#   {flag} " in header, f"flag {flag!r} is undocumented"


def _wrapper_from_spec_formula(payload: bytes) -> str:
    """Build a wrapper straight from A.8.2.2 and A.8.3.1, independent of src/.

    Deliberately NOT importing the package. This is the specification transcribed a
    second time, so that the vector file is validated against the spec rather than
    against our own encoder. A fixture generated by calling our code and asserted
    against our code proves only that a function is its own inverse.
    """
    import struct

    magic = bytes.fromhex("4332504154585400")
    body = magic + bytes([1]) + struct.pack(">I", len(payload)) + payload
    # "﻿" spelled as an escape, never as a literal: an invisible character in
    # source is unreviewable, and this file is about invisible characters.
    return "\ufeff" + "".join(chr(0xFE00 + b) if b <= 0x0F else chr(0xE0100 + (b - 16)) for b in body)


@pytest.mark.parametrize(
    "vector",
    [v for v in VECTORS if v.op == "embed" and v.is_ok],
    ids=vector_id,
)
def test_embed_records_match_the_spec_formula(vector: Vector) -> None:
    """expect == text || U+FEFF || selector-encoded wrapper, per A.8."""
    text = vector.text.decode("utf-8")
    derived = (text + _wrapper_from_spec_formula(vector.payload)).encode("utf-8")
    assert derived == vector.expect


def test_e0001_reproduces_the_encypher_golden_vector() -> None:
    """Three-way interop anchor.

    EncypherAI's golden/vectors.json "ascii_small" record is "hello world" with a
    deadbeef payload. Matching it byte for byte is stronger evidence of correctness
    than any assertion we write about ourselves.
    """
    e0001 = next(v for v in VECTORS if v.id == "E0001")
    assert e0001.text == b"hello world"
    assert e0001.payload == bytes.fromhex("deadbeef")
    assert e0001.expect.hex() == (
        "68656c6c6f20776f726c64efbbbff3a084b3f3a084a2f3a08580f3a084b1f3a08584f3a08588"
        "f3a08584efb880efb881efb880efb880efb880efb884f3a0878ef3a0869df3a086aef3a0879f"
    )


def test_extract_success_records_carry_a_locatable_wrapper() -> None:
    """Every OK extract record's text must actually contain its expected payload."""
    for vector in (v for v in VECTORS if v.op == "extract" and v.is_ok):
        text = vector.text.decode("utf-8")
        assert _wrapper_from_spec_formula(vector.expect) in text, vector.id


#: SHA-256 of the manifest store produced by a fully pinned ``embed``, and of the
#: marked text carrying it. Regenerate ONLY as part of a deliberate MAJOR release.
_GOLDEN_STORE_SHA256 = "351ca402ffacc0b4b59433fd19893b74b20cbd5c69068a07155632f8bad01251"
_GOLDEN_MARKED_SHA256 = "3b51db34f58d4cba6cfbd6b4940583e738b211f821bab06f0e7bf3b0b4a80a01"
_GOLDEN_STORE_BYTES = 1824


def test_the_signed_manifest_bytes_are_exactly_what_they_were() -> None:
    """CONTRIBUTING.md: "Any change to the bytes we emit is a MAJOR version of both this
    package and the conformance vector file." UNTIL NOW NOTHING ENFORCED THAT FOR THE
    MANIFEST, and the rule was aspirational rather than checkable.

    Demonstrated: changing ``_cose``'s x5chain encoding from "bare certificate when
    there is one" to "always a list" moves the store from 1824 to 1828 bytes under this
    test's own pinned context, and every other test passes. The vector file cannot catch
    it and says so: it pins the bytes of the WRAPPER, the carrier, not the manifest
    inside it. The published-size test has a band a four-byte change slides under.

    THE FIGURES WERE WRONG HERE ONCE, as "1790 to 1793" -- taken under a different
    context from the one this test pins, and contradicting ``_GOLDEN_STORE_BYTES``
    five lines above. Measure the delta under the context the assertion uses, or the
    number describes a build nothing checks. Under ``test_embed.PINNED`` the same
    change makes the store one byte SMALLER, because the padding fixpoint absorbs it.

    The same gap let the ORDER of ``_assertions_and_claim``'s assertion list change
    silently, which reorders ``created_assertions`` inside the SIGNED claim.

    EVERY NON-DETERMINISTIC INPUT IS PINNED -- both UUIDs, the clock, the certificate
    serial -- so this is a pure function of the code. Verified byte-identical across
    repeated runs, and an earlier audit verified the same construction across Python
    3.10 and 3.12.

    WHEN THIS FAILS, DO NOT UPDATE THE CONSTANT TO MAKE IT PASS. It is telling you the
    wire changed. Either revert the change, or take the MAJOR version on both this
    package and the vector file, regenerate, and confirm that text marked by the
    previous version still verifies -- which is the property the rule exists to protect.
    """
    import datetime
    import hashlib
    import uuid

    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    from c2patxt import EmbedContext, embed, extract
    from c2patxt.signing import Signer
    from tests.conftest import DISCLOSURE, build_certificate

    key = Ed25519PrivateKey.from_private_bytes(bytes(range(32)))
    signer = Signer(private_key=key, certificates=(build_certificate(key),))
    context = EmbedContext(
        manifest_uuid=uuid.UUID("00000000-0000-4000-8000-000000000001"),
        instance_id="xmp:iid:00000000-0000-4000-8000-000000000002",
        when=datetime.datetime(2026, 6, 1, 12, 0, tzinfo=datetime.timezone.utc),
    )

    marked = embed("Hello world.", signer, DISCLOSURE, context=context)
    store = extract(marked)
    assert store is not None

    assert len(store.raw) == _GOLDEN_STORE_BYTES, f"the manifest store is now {len(store.raw)} B"
    assert hashlib.sha256(store.raw).hexdigest() == _GOLDEN_STORE_SHA256, "the SIGNED MANIFEST bytes changed"
    assert hashlib.sha256(marked.encode("utf-8")).hexdigest() == _GOLDEN_MARKED_SHA256, "the MARKED TEXT changed"
